super_admin_1/models/shop_logs.py
super_admin_1/shop/del_shop.py
super_admin_1/shop/shoplog_helpers.py

- Closes issue #10 
- implement shop logging database model class
- implement  shop logging helper functions
- log shop deleted
- log shop created
- log shop reviewed
- log shop admin status
- log shop restricted
- show sample logging usage in delete shop endpoint
- implement get shop logs enpoint
- implement download shop logs endpoint

 Feat: implement shop or vendor loggin

---

fetch_data.py
insert_data.py
super_admin_1/__init__.py
super_admin_1/models/alternative.py
super_admin_1/shop/ban_vendor.py

This PR closes #7 
https://linear.app/zuri-project-backend/issue/SUP-11/develop-api-endpoints-to-ban-vendor-accounts
I created dummy data using Mockaroo and used wrote a script that contained queries to create dummy users and shops to test my endpoint.

 #7 - API Endpoints to Ban Vendor Account

---

api-documentation.md

This API documentation provides comprehensive information on how to use the API for a user and event management system. It covers various aspects, including error handling, user management, shop management, and product management. Here is a brief overview of the key sections:
Introduction: Provides an introduction to the API and its purpose, welcoming users to the documentation.
Error Handling: Describes how the API handles errors, including common error responses with status codes and error messages.
User Class: Explains the API endpoint for managing user information and details the methods available, such as retrieving users, creating users, updating user information, and deleting users.
Shop Class Template: Introduces the structure of the Shop class, which is part of a larger Python …

Zainab documentation 

---

super_admin_1/shop/restore_shop.py

restore the deleted shop by changing the status from temporary to active

retored deleted shop  by changing their status from "temporary" to "active"

---

super_admin_1/shop/del_shop.py

Fixed the base model with the right default context for all other class that will inherit from it
Update the route base on the new db schema
A new user object was created
A new shop object was created base on the user-id
The shop object was modified using the API endpoint associated with it
PostMan testing Environment
```
curl --location 'http://127.0.0.1:5000/sa/api/user/create' \
--header 'Content-Type: application/json' \
--data-raw '{
"username": "Freema",
"first_name": "Wonderfl",
"last_name": "Faria",
"email": "1abdul@abdul.com",
"section_order": "7Mobile",
"password": "7test123",
"is_verified": true,
"two_factor_auth": true,
"provider": "7ubuntu",
"profile_pic": "7hi",
"refresh_token": "7welcome123",
"location": "Lagos",
"country": "Nigeiria"
}'
```
###Response
```
{
"country": …
```

docs: :memo: proper 404 message

---

super_admin_1/models/shop_logs.py
super_admin_1/shop/del_shop.py
super_admin_1/shop/shoplog_helpers.py

​
​- Fix Shoplogs database model class
- remove admin name and shop name from model
​
​- inconsistent database representation in schema and model class
​
​

fix: shoplogs database model

---

run.py
super_admin_1/products/delete_product.py
super_admin_1/products/event_logger.py

Added my endpoint to the product blueprint
​
Adjusted the file structure for product logs
​
​
​
​
​
​

adjusting the schema

---

super_admin_1/__init__.py
super_admin_1/products/delete_product.py

[linear ticket](https://linear.app/zuri-project-backend/issue/SUP-15/develop-api-endpoints-to-remove-or-delete-product-listings) 
#5 
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.

Feat: Endpoint to Temporarily Delete Product 

---

super_admin_1/__init__.py
super_admin_1/products/delete_product.py
super_admin_1/products/event_logger.py
super_admin_1/products/restore_product.py

Endpoint to temporarily Delete a Product
[linear ticket](https://linear.app/zuri-project-backend/issue/SUP-15/develop-api-endpoints-to-remove-or-delete-product-listings) 
#5 
It Develop API endpoint to delete product listing. Ensure that the product is not deleted permanently, but is sent to the deleted products page of the product listing overview screen in the admin dashboard. Deleted products will also be removed from the marketplace and vendor shop.
An already created Product_id is parsed into the URl path and, that is used to query and edit product "is_deleted" status to "temporarily.

Fix: Endpoint to Temporarily Delete Product

---

.github/workflows/keep-awake.yml
super_admin_1/shop/ban_vendor.py

​
This change is to include a cron job that wakes the live server every 5 minutes
​
​

Add GitHub Actions workflow to keep service awake

---

super_admin_1/models/base.py
super_admin_1/models/product.py
super_admin_1/models/shop.py
super_admin_1/models/user.py
super_admin_1/shop/del_shop.py

​
Code base refactor
​
​
​
​
​
​

feat: :sparkles: refactor to current db schema

---

.gitignore
admin_actions_2023_10_09.txt
fetch_data.py
insert.py
super_admin_1/products/delete_product.py

This pull request addresses the ticket titled "Develop API endpoints to permanently delete product listings" by adding a new API endpoint for permanent product deletion.
[Link to Linear Ticket](https://linear.app/zuri-project-backend/issue/SUP-24/develop-api-endpoints-to-permanently-delete-product-listings)
The ticket requested the development of an API endpoint for permanently deleting product listings. This change fulfills that requirement by introducing the `/permanent/<id>` endpoint for irreversible product deletion.
I thoroughly tested this code in a local development environment by:
- Setting up a PostgreSQL database.
- Running the provided `fetch_data.py` script and testing the endoint to ensure it works.
- Verifying that products were permanently deleted with appropriate error …

added an endpont to permanently delete a produxt listing

---

super_admin_1/products/event_logger.py
super_admin_1/shop/del_shop.py

deployment fix

---

super_admin_1/shop/del_shop.py
super_admin_1/shop/restore_shop.py
super_admin_1/shop/shoplog_helpers.py

Implement the function to log actions in Shop Create, Shop Delete and Shop Restore endpoints
​
Log shop create action 
Log shop delete action 
Log shop restore action
Add function to log shop ban
Add function to log shop unban
​
​
Improve on previous work on #11 
​
Testing done locally
​
​
- [ x] Bug fix (non-breaking change which fixes an issue)
​

Add log function to endpoints

---

super_admin_1/tests/product-test.py
super_admin_1/tests/shop-test.py
super_admin_1/tests/vendors-test.py

created pytests for the shop  and products endpoints
​
'
created a new folder where all the tests live
​
https://linear.app/zuri-project-backend/issue/SUP-25/write-internal-test-suits-for-super-admin-api
​
tests endpoints for the shp and products
​
​
​
- [ x] New feature (non-breaking change which adds functionality)
​

add pytests

---

super_admin_1/products/delete_product.py
super_admin_1/products/restore_product.py
super_admin_1/shop/ban_vendor.py
super_admin_1/shop/del_shop.py
super_admin_1/shop/restore_shop.py
super_admin_1/shop/shop_activity.py
super_admin_1/shop/unban_vendor.py
super_admin_1/tests/wrapper-test.py
utils.py

​
Created a wrapper function to authenticate super admin
​
https://linear.app/zuri-project-backend/issue/SUP-29/authorizations-for-each-endpoint
​
​
​
​
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
​
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

add decorator for authentication

---

super_admin_1/models/base.py
super_admin_1/models/product.py
super_admin_1/models/product_image.py
super_admin_1/models/shop.py
super_admin_1/models/user.py
super_admin_1/models/user_product_rating.py

Updated DB-Models based on changes made to the Schema
​
Updated Product Model: rating_id, image_id,
Updated product_image Model
Updated user_product_rating Model
Updated Base model
Updated User Model 
​
https://linear.app/zuri-project-backend/issue/SUP-28/database-schema-creation
​
This change is required because the database was updated
​
Each models class above was tested thoroughly and instances was created of each before making this PR
​
​
​
- [yes] My code follows the code style of this project.
- [yes] My change requires a change to the documentation.
- [yes] I have updated the documentation accordingly.
- [yes ] I have read the **CONTRIBUTING** document.
- [yes] I have added tests to cover my changes.
- [yes] All new and existing tests passed.

SCHEMA UPDATE MADE TO DB-MODELS

---

super_admin_1/models/product.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

Endpoint information was provided and duplicate object constructor for product model was removed
​
Included the endpoint information in docstring
Removed duplicate __init__ method 
​
#81
​
To provide detailed information related to each endpoint.
​
​
​
​

Update shop and product docstring info

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py

To temporarily delete or ban a shop or a product, require the user to supply a reason for this.
​
​
https://linear.app/zuri-project-backend/issue/SUP-36/accept-reason-as-payload-for-temp-delete-and-banning
​
​
​
​
- [x ] Bug fix (non-breaking change which fixes an issue)
​
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

allow a json payload with temporary delete or ban

---

super_admin_1/logs/routes.py
super_admin_1/notification/notification_helper.py
super_admin_1/notification/routes.py
super_admin_1/products/routes.py

Notification implementation

---

super_admin_1/products/routes.py

Implemented APIS on Sanction MAnagement
/api/product/sanction/<product_id> [PATCH]- API sanction a product by product id
/api/product/remove_sanction/<product_id> [PATCH] - API to remove sanction on a product by product id
/api/product/sanctioned_products/  [GET]- API to get all sanctioned products
/api/product//get-all-products/ [GET]- API get all products with only specific details
/api/product/sanctioned_product/<product_id> [GET] - API to get the details of a particular product by product id
/api/product/sanctioned_product/<product_id> [DELETE] - API to permanently delete a sanctioned product
/api/product/restore_product/<product_id> [PATCH] - API to restore a temporarily deleted product
/api/product//product_statistics [GET] - API to get statistics on total product, sanctioned …

Implement Sanction Management

---

super_admin_1/products/product_schemas.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

​apply user input Validation using pydantic
- this is closed the ticket to screen user inputs to ensure only valid data is sent to the database
- fix bugs breaking code in products and shops routes
​
​- to ensure valid input strings are being handled by the database and the client is explained what input fields have issues and what the issue is
​- live testing with postman
​
​

Product input validation

---

super_admin_1/logs/routes.py
super_admin_1/products/routes.py
super_admin_1/shop/func_helpers.py
super_admin_1/shop/routes.py
utils.py

​
​- Refactor super admin decorator 
​
​

Fix super admin auth request decorator

---

super_admin_1/__init__.py
super_admin_1/shop/routes.py

shop logs routes was removed adding back

fix missing shop log blueprint

---

super_admin_1/products/routes.py

slight changes

---

super_admin_1/products/routes.py

added notification function to product action routes

---

super_admin_1/db_utils.py

Created db_utils file with query helper functions
​
Created new file db_utils that helps query the DB
​
https://linear.app/zuri-project-backend/issue/SUP-38/query-helper-functions
​
To make it easier to query DB
The get user endpoint was used to test the db_utils functions
It queried the database for a user using the user_id
​
​
​

Query Helper Functions

---

super_admin_1/products/routes.py
utils.py

Fix: Repeated Codes and handles Reponses

---

super_admin_1/__init__.py
super_admin_1/shop/routes.py

Reverts hngx-org/spitfire-super-admin-one#106
Shop logs has been moved to logs blueprint

Revert "fix missing shop log blueprint"

---

super_admin_1/products/routes.py

​i changed the logic of sanction from blacklisted to suspended
Restore product API, after confirming if the product.is_deleted is temporary also check and turn the product.admin_status to approved
​
​
​
​
​
​
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

Modified product samuel - changed the logic of sanction from blacklisted to suspended

---

super_admin_1/models/product.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

for Fe testing and integration

Test:remove auth for shop

---

super_admin_1/products/routes.py

Resolve conflict

---

super_admin_1/products/routes.py

​
​
​
​
​
​
- [x Bug fix (non-breaking change which fixes an issue)
​

feat: :sparkles: authentication decorator on all API routes

---

super_admin_1/shop/routes.py

Authentication added to all routes

---

super_admin_1/products/routes.py

​
Updated Restore product route to effectly turn admin status to approved after restoring \
​
​
​
​
​
​

Updategd Restore product route

---

health_check.py
super_admin_1/logs/routes.py
super_admin_1/notification/routes.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

feat: :sparkles: Add "admin" to the API routes

---

super_admin_1/products/routes.py
utils.py

Feat: Approve PRoduct Endpoint

---

collection.py
super_admin_1/shop/collection.py
swagger_config.yaml

Fix: Removal of Redundant Endpoints

---

super_admin_1/models/product.py

Updated to make sure sanction and restoring works

---

super_admin_1/products/routes.py
swagger_config.yaml

Feat: Docs for Extra Endpoints (Products)

---

super_admin_1/notification/config.py
super_admin_1/notification/notification_helper.py
super_admin_1/notification/routes.py
super_admin_1/products/routes.py

Feat: notification for products

---

super_admin_1/products/routes.py

Fix: Permanent Delete endpoint

---

super_admin_1/logs/routes.py
super_admin_1/notification/notification_helper.py
super_admin_1/notification/routes.py

Fix: cleaning up

---

LICENSE
README.md

Add the license file to the readme

---

super_admin_1/shop/routes.py

Bug: removed reason

---

super_admin_1/shop/routes.py

muddied the water

---

utils.py

decorator updat

---

super_admin_1/notification/notification_helper.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

Notification and Reason Update

---

super_admin_1/shop/routes.py

Temp Delete shop updated

---

super_admin_1/shop/routes.py
utils.py

fix: BAn vendor error

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py

fix: temporary deletion

---

super_admin_1/shop/routes.py

Fix : delete_shop

---

super_admin_1/notification/notification_helper.py
super_admin_1/notification/routes.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

Fix: Unban shop

---

super_admin_1/products/routes.py

Fix: get products product_status

---

super_admin_1/shop/routes.py

​
* A temporarily deleted producted shouldn't get banned again and vice versa
​
​
​
​
​
​

Prevent Cross Actions

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py
utils.py

Feat: added image to product related endpoints

---

super_admin_1/shop/routes.py

Add merchants location and country to get shops/shop endpoints

Add merchant location and merchant country to shops/shop endpoint

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py
utils.py

- addition for vendor management screen

Vendor profile image

---

super_admin_1/models/product_category.py
super_admin_1/models/product_sub_category.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

​
Added a new data field for the product and shop routes
```category_name , and sub_category_name```
Added new model for product_sub_category
​
​
​
​
```
{
"data": [
{
"admin_status": "pending",
"category_id": 4,
"category_name": "computer enginering",
"createdAt": "Sun, 15 Oct 2023 14:27:14 GMT",
"currency": "$",
"description": "No vex I like game",
"discount_price": "0.00",
"is_deleted": "active",
"is_published": false,
"price": "28000.00",
"product_id": "3c00b3f7-d7ee-40cb-8b1a-e86b366dbae6",
"product_image": [],
"product_name": "DevC Pad",
"product_status": "Active",
"quantity": 4,
"rating_id": null,
"shop_id": "2c9236e6-92d0-4347-8e27-21750dbc8cf0",
"shop_name": "Harpoon Shop",
"sub_category_name": "backend enginering",
"tax": "0.00",
"updatedAt": "Sun, 15 Oct 2023 14:27:14 GMT", …
```

feat: :sparkles: added new attributes to the data fields of shop and product

---

super_admin_1/notification/notification_helper.py

update: reason entry update for store notification

---

super_admin_1/shop/routes.py
utils.py

Include total orders and total sales for vendor to the data response.

Add orders and sales field

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py
utils.py

​
​- null values associated with the vendor profile picture 
- fix empty list vor total vendor sales and order
​
​
​
​

Fix: null values 

---

super_admin_1/shop/routes.py

​
Ensure a change in object state matches the criteria for the object status
​
​
​
​
​
​

feat: :sparkles: ensure object stauts fulfills the status criteria

---

super_admin_1/db_utils.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

​
​- Pagination
​
​
​
- Postman, etc):
​
​

Fix: Pagination

---

super_admin_1/shop/routes.py

​
​This implements pagination for the products belonging to a shop in the get shop endpoint `/api/admin/shop/<shop_id>`
- it would return total number of products 
- total number of pages
- and the products for the shop (max of 10 products per page)
​
- to reduce the size of response object from the server
- To ensure the client is not not bombarded with unnecessary data 
​
- Live testing on postman passing a page query parameter and not passing one
​
​

paginate shop products

---

super_admin_1/shop/routes.py

Pagination for vendor management
​
* paginate the response, and send the total number of pages
* receive a query param to send the exact data for the page
* search based on name
* filter search result based on status
​
​
* We can't return all the data from the database, so pagination has to be done from the server
​
* Hitting the endpoint through Thunderclient
​
​
​

Pagination, filter, search

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py

​
​- set up pagination in all product route to reduce erver over load
- Added query parameters for product status and product search
​
​
​
- Postman, etc):
​
​

Feat: Pagination, search Query and Status Query in product

---

super_admin_1/notification/notification_helper.py
super_admin_1/shop/routes.py

Added an extra condition to the check status function
​
* Fixed the sql query to the db
* Added an extra condition to enable status recognition
​
​
​
​
​
​

Fix: get shop and notification fix

---

.github/workflows/keep-awake.yml
super_admin_1/notification/notification_helper.py
super_admin_1/shop/routes.py

Fix: Render server

---

super_admin_1/products/routes.py

​
- implement get all products based on product name search and product status query params
​
- ensure client can perform server side filtering of data based on product name and status
​
​- live testing on postman using production database and local server
​
​

Product search

---

health/helpers.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

Pending product addition

---

health/__init__.py
super_admin_1/__init__.py
super_admin_1/errors/handlers.py
super_admin_1/logs/routes.py
super_admin_1/notification/routes.py
super_admin_1/products/routes.py
super_admin_1/shop/routes.py

- ​Versioned all API endpoints 
- pluralized endpoints from singular references to plural 
​- ​Versioned all API endpoints from `/api/admin/product` to `/api/v1/admin/product`
- pluralized endpoints form singular references to plural `/api/v1/admin/products` and so on
​
​Boss @zxenonx  ordered it be done!
​- all refactored endpoints were tested using postman
​
​

Feat:versioning API

---

super_admin_1/errors/handlers.py
super_admin_1/products/routes.py

**Code clean up for improper products validation error handling**
​- refactored redundant validation check code in product routes
- moved validation error class to general app error handler
- remove validation checks from try except blocks
​- To make code base DRY
- to follow industry production standards
- 
​- live testing with postman and incorrect fuzz inputs 
​

refactor validation error handling

---

health/endpoints/customer_purchase.py
health/endpoints/market_place.py
health/helpers.py
health/routes.py

Fix: Minor Corrections in Endpoints Config

---

swagger_config.yaml

​
Update swagger docs to reflect new endpoint changes.
​
None.
​
​
​
​
​

[Docs]: Update swagger docs

---

super_admin_1/shop/routes.py

Remove raise_validation erro

---

super_admin_1/shop/routes.py

​
Bug issue: variable name same as a built in keyword
​
​
This will ensure no shadow names confliction
​
​
```` http://127.0.0.1:5000/api/v1/admin/products/all ````
```
{
"data": [
{
"admin_status": "suspended",
"category_id": 474,
"category_name": "Development & Programming",
"createdAt": "Thu, 19 Oct 2023 17:12:24 GMT",
"currency": "NGN",
"description": "ssssddcdewcdscdscdsc",
"discount_price": "0.00",
"is_deleted": "active",
"is_published": false,
"price": "4000.00",
"product_id": "aeb910a3-2e84-4268-ac81-e56509f718a4",
"product_image": [],
"product_name": "booooo",
"product_status": "Sanctioned",
"quantity": 1,
"rating_id": null,
"shop_id": "438b5512-267c-40e2-9545-0805f9dc8b88",
"shop_name": "Brown-Medina",
"sub_category_name": "Web Development",
"tax": "10.00",
"updatedAt": "Fri, 20 …
```

fix: :bug: BUG: replaced variable having the same name as a built-in keyword

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py
utils.py

THE CLEANSE!

---

health/routes.py

Fix: Uncommenting Code

---

super_admin_1/products/routes.py
super_admin_1/shop/routes.py

🐛 Bug fixes 
Provide a general summary of your changes in the Title above 
​
fixes the type in restore_shop
​
If fixing a bug, there should be an issue describing it with steps to reproduce 
​
​
​
​
​
cklist:
Go over all the following points, and put an `x` in all the boxes that apply. 
If you're unsure about any of these, don't hesitate to ask. We're here to help!

🐛 BUG fix:  extract and validate in same line by removing redundancy, typo fixes

---

super_admin_1/products/routes.py
utils.py

​/api/v1/admin/products/filters
param
filter [status, newest, oldest]
{
"data": [],
"date_requested": date and time,
"message": "All products information by {filter_param}",
"total_deleted_products": 0,
"total_pages": 0,
"total_products": 0,
"total_sanctioned_products": 0
}
​
​
​
​
​
​

Endpoint to filter product based on status, newest and oldest
